plugins = []
headers = []
redirects = []

[functions]

[functions."*"]

[build]
publish = "/Users/baptistegresse/Documents/webflow_test/auto-homepage"
publishOrigin = "default"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]